### ISSUE TITLE
Package not available

### ISSUE THREAD

**Issue by dsnoeck** [fortean/laravel-festivus#1]
First, in the Readme, Installation chapter, it should be something like: fortean/laravel-festivus, no ?
Then, this package is not available on packagist.org.

**Comment by bmwalter68** [comment]
Hey Snoeck, thanks for the email.  I didn't add to packagist yet because 
I'm still making a few core changes that would affect how it 
integrates.  That's also the reason for the documentation lagging. It's 
on git at this point so some folks can get eyeballs on it. Since the 
project it's used for is almost done, it will likely be on packagist soon.
- Bruce

**Comment by bmwalter68** [comment]
I've committed versions for both Laravel 4 & Laravel 5 and added the repo to Packagist.
